=== MaTriXy/tensorio-ios/TensorIO/Assets/Federated/task-schema.json
{
  "$schema":  "http://json-schema.org/draft-07/schema#",
  "$id":      "https://github.com/doc-ai/tensorio/schemas/v0.9.0/tiotask/schema.json",

  "definitions": {
    
    "model": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id"
      ],
      "properties": {
        "id": { "type": "string" }
      }
    },

    "placeholder.array.quantize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias":     { "type": "number" }
          }
        }
      ]
    },

    "placeholder.array": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "name",
        "type",
        "shape",
        "value"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["array"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8", "float32", "int32", "int64"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "quantize": {
          "$ref": "#/definitions/placeholder.array.quantize"
        },
        "value": {
          "type": "array",
          "items": { "type": "number"  }
        }
      }
    },

    "placeholders": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/placeholder.array" }
        ]
      }
    },

    "taskParameters": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "numEpochs",
        "batchSize"
      ],
      "properties": {
        "numEpochs":    { "type": "integer" },
        "batchSize":    { "type": "integer" },
        "shuffle":      { "type": "boolean" },
        "placeholders": { "$ref":  "#/definitions/placeholders" }
      }
    }

  },

  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "details",
    "id",
    "task",
    "model",
    "taskParameters"
  ],
  "properties": {
    "name":             { "type": "string" },
    "details":          { "type": "string" },
    "id":               { "type": "string" },
    "model":            { "$ref": "#/definitions/model" },
    "taskParameters":  { "$ref": "#/definitions/taskParameters" },
    "task":             {
      "type": "string",
      "enum": ["train"]
    }
  }
}

=== MaTriXy/tensorio-ios/FederatedExample/FederatedExample/task-tests/cats-vs-dogs-train-with-placeholder.tiotask/task.json
{
  "id": "cats-vs-dogs-v2-100-128-unquantized-task",
  "name": "Cats vs dogs example training test",
  "details": "",
  "task": "train",
  "model": {
    "id": "cats-vs-dogs-v2-100-128-unquantized"
  },
  "taskParameters": {
    "numEpochs": 10,
    "batchSize": 2,
    "shuffle": false,
    "placeholders": [
      {
        "name": "placeholder_adam_learning_rate",
        "type": "array",
        "dtype": "float32",
        "shape": [1],
        "value": [0.001]
      }
    ]
  }
}
