=== MaTriXy/tensorio-ios/TensorIO/Assets/TFLite/model-schema.json
{
  "$schema":  "http://json-schema.org/draft-07/schema#",
  "$id":      "https://github.com/doc-ai/tensorio/schemas/v0.7.0/tflite/schema.json",

  "definitions": {
    
    "model": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "file",
        "quantized"
      ],
      "properties": {
        "file":       { "type":   "string"  },
        "quantized":  { "type":   "boolean" },
        "type":       { "type":   "string"  },
        "backend":    { "type":   "string",
                        "const":  "tflite"  },
        "class":      { "type":   "string"  },
        "modes":      {
          "type": "array",
           "items": {
            "type": "string",
            "enum": ["predict"]
          }
        }
      }
    },

    "options": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "device_position":  { "type": "string" },
        "output_format":    { "type": "string" }
      }
    },

    "input.quantize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias":     { "type": "number" }
          }
        }
      ]
    },

    "input.scalar": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["scalar"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8", "float32"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "quantize": {
          "$ref": "#/definitions/input.quantize"
        }
      }
    },

    "input.array": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["array"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8", "float32"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "quantize": {
          "$ref": "#/definitions/input.quantize"
        }
      }
    },

    "input.image.normalize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "r":    { "type": "number" },
                "g":    { "type": "number" },
                "b":    { "type": "number" }
              }
            }
          }
        }
      ]
    },

    "input.image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape",
        "format"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["image"]
        },
        "name": {
          "type": "string"
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "format": {
          "type": "string",
          "enum": ["RGB", "BGR"]
        },
        "normalize": {
          "$ref": "#/definitions/input.image.normalize"
        }
      }
    },

    "input.string": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape",
        "dtype"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["string"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8", "float32"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        }
      }
    },

    "output.dequantize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias":     { "type": "number" }
          }
        }
      ]
    },

    "output.scalar": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["scalar"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8", "float32"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "dequantize": {
          "$ref": "#/definitions/output.dequantize"
        }
      }
    },

    "output.array": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["array"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8", "float32"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "labels": {
          "type": "string"
        },
        "dequantize": {
          "$ref": "#/definitions/output.dequantize"
        }
      }
    },

    "output.image.denormalize": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "standard": { "type": "string" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "scale":    { "type": "number" },
            "bias": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "r":    { "type": "number" },
                "g":    { "type": "number" },
                "b":    { "type": "number" }
              }
            }
          }
        }
      ]
    },

    "output.image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape",
        "format"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["image"]
        },
        "name": {
          "type": "string"
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "format": {
          "type": "string",
          "enum": ["RGB", "BGR"]
        },
        "denormalize": {
          "$ref": "#/definitions/output.image.denormalize"
        }
      }
    },

    "output.string": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "shape",
        "dtype"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["string"]
        },
        "dtype": {
          "type": "string",
          "enum": ["uint8", "float32"]
        },
        "shape": {
          "type": "array",
          "items": { "type": "integer" }
        }
      }
    }

  },
  
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "details",
    "id",
    "version",
    "author",
    "license",
    "model",
    "inputs",
    "outputs"
  ],
  "properties": {
    "name":         { "type": "string" },
    "details":      { "type": "string" },
    "id":           { "type": "string" },
    "version":      { "type": "string" },
    "author":       { "type": "string" },
    "license":      { "type": "string" },
    "placeholder":  { "type": "boolean" },
    "model":        { "$ref": "#/definitions/model" },
    "inputs": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/input.array"  },
          { "$ref": "#/definitions/input.image"  },
          { "$ref": "#/definitions/input.string" }
        ]
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/output.array"  },
          { "$ref": "#/definitions/output.image"  },
          { "$ref": "#/definitions/output.string" }
        ]
      }
    },
    "options": { "$ref": "#/definitions/options" }
  }
}

=== MaTriXy/tensorio-ios/TensorFlowExample/models-tests/2_in_2_out_matrices_test.tfbundle/model.json
{
	"name": "1 in 2 out matrices test",
	"details": "Simple model with two matrix input nodes and two matrix output nodes",
	"id": "2_in_2_out_matrices_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"model": {
		"file": "predict",
		"quantized": false,
		"class": "TIOTensorFlowModel"
	},
	"inputs": [
		{
			"name": "input_X",
			"type": "array",
			"shape": [4,4]
		},
		{
			"name": "input_Y",
			"type": "array",
			"shape": [4,4]
		}
	],
	"outputs": [
		{
			"name": "output_Z",
			"type": "array",
			"shape": [4,4]
		},
		{
			"name": "output_S",
			"type": "array",
			"shape": [4,4]
		}
	]
}

=== MaTriXy/tensorio-ios/DeployExample/DeployExample/upgradable.tiobundle/model.json
{
	"name": "Upgradable Model For Testing",
	"details": "",
	"id": "tio:///models/happy-face/hyperparameters/batch-9-2-0-1-5/checkpoints/model.ckpt-321312",
	"version": "1",
	"author": "doc.ai",
	"license": "Apache 2.0",
	"model": {
		"file": "touch.tflite",
		"quantized": false,
		"type": "image.classification.imagenet",
		"backend": "tflite"
	},
	"inputs": [
		{
			"name": "image",
			"type": "image",
			"shape": [128,128,3],
			"format": "RGB"
		}
	],
	"outputs": [
		{
			"name": "classification",
			"type": "array",
			"shape": [1,1000],
			"labels": "labels.txt",
			"dequantize": {
				"standard": "[0,1]"
			}
		}
	],
	"options": {
		"device_position": "back",
		"output_format": "image.classification.imagenet"
	}
}

=== MaTriXy/tensorio-ios/TensorFlowExample/models-tests/no-backend.tiobundle/model.json
{
	"name": "1 in 1 out numeric test",
	"details": "Simple model with a single valued input and single valued output",
	"id": "no_backend_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"model": {
		"file": "predict",
		"quantized": false,
		"modes": ["predict"]
	},
	"inputs": [
		{
			"name": "input",
			"type": "array",
			"shape": [1]
		}
	],
	"outputs": [
		{
			"name": "output",
			"type": "array",
			"shape": [1]
		}
	]
}

=== MaTriXy/tensorio-ios/TensorFlowExample/models/cats-vs-dogs.tfbundle/model.json
{
	"name": "Cats vs Dogs MobileNet V2 1.0 128",
	"details": "Cats vs Dogs Kaggle model based on MobileNet V2 architecture with a width multiplier of 1.0 and an input resolution of 128x128.",
	"id": "cats-vs-dogs-v2-100-128-unquantized",
	"version": "1",
	"author": "doc.ai",
	"license": "Apache License. Version 2.0 http://www.apache.org/licenses/LICENSE-2.0",
	"model": {
		"file": "predict",
		"quantized": false,
		"type": "image.classification.catsvsdogs",
		"class": "TIOTensorFlowModel"
	},
	"inputs": [
		{
			"name": "image",
			"type": "image",
			"shape": [224,224,3],
			"format": "RGB",
			"normalize": {
				"scale": 0.0078,
				"bias": {
					"r": -1,
					"g": -1,
					"b": -1
				}
			}
		}
	],
	"outputs": [
		{
			"name": "classification",
			"type": "array",
			"shape": [1,1000],
			"labels": "labels.txt"
		}
	],
	"options": {
		"device_position": "back"
	}
}

=== MaTriXy/tensorio-ios/Example/models-tests/1_in_1_out_string_test.tiobundle/model.json
{
	"name": "1 in 1 out numeric test",
	"details": "Simple model with a single valued input and single valued output",
	"id": "1_in_1_out_string_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"model": {
		"file": "model.tflite",
		"quantized": false,
		"backend": "tflite",
		"modes": ["predict"]
	},
	"inputs": [
		{
			"name": "input",
			"type": "string",
			"dtype": "float32",
			"shape": [1]
		}
	],
	"outputs": [
		{
			"name": "output",
			"type": "string",
			"dtype": "float32",
			"shape": [1]
		}
	]
}

=== MaTriXy/tensorio-ios/DeployExample/DeployExample/testsetup.tiobundle/model.json
{
	"name": "Upgradable Model For Testing",
	"details": "An upgradable model",
	"id": "tio:///models/TestModel-1558049870/hyperparameters/hyperparameters-1/checkpoints/checkpoint-1",
	"version": "1",
	"author": "doc.ai",
	"license": "Apache 2.0",
	"model": {
		"file": "touch.tflite",
		"quantized": false,
		"type": "image.classification.imagenet",
		"backend": "tflite"
	},
	"inputs": [
		{
			"name": "image",
			"type": "image",
			"shape": [128,128,3],
			"format": "RGB"
		}
	],
	"outputs": [
		{
			"name": "classification",
			"type": "array",
			"shape": [1,1000],
			"labels": "labels.txt",
			"dequantize": {
				"standard": "[0,1]"
			}
		}
	],
	"options": {
		"device_position": "back",
		"output_format": "image.classification.imagenet"
	}
}

=== MaTriXy/tensorio-ios/TensorFlowExample/models-tests/1_in_1_out_pixelbuffer_identity_test.tfbundle/model.json
{
	"name": "1 in 1 out pixel buffer identity test",
	"details": "Outputs the input pixel buffer. Made to test the normalization and denormalization functions.",
	"id": "1_in_1_out_pixelbuffer_identity_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"model": {
		"file": "predict",
		"quantized": false,
		"class": "TIOTensorFlowModel"
	},
	"inputs": [
		{
			"name": "input_x",
			"type": "image",
			"shape": [224,224,3],
			"format": "RGB",
			"normalize": {
				"standard": "[0,1]"
			}
		}
	],
	"outputs": [
		{
			"name": "output_z",
			"type": "image",
			"shape": [224,224,3],
			"format": "RGB",
			"denormalize": {
				"standard": "[0,1]"
			}
		}
	]
}

=== MaTriXy/tensorio-ios/Example/models-tests/1_in_1_out_tensors_test.tfbundle/model.json
{
	"name": "1 in 1 out tensors test",
	"details": "A more complex model with a single 3 dimensional tensor for an input and one for an output",
	"id": "1_in_1_out_tensors_test",
	"version": "1",
	"author": "doc.ai",
	"license": "",
	"model": {
		"file": "model.tflite",
		"quantized": false,
		"backend": "tflite"
	},
	"inputs": [
		{
			"name": "input",
			"type": "array",
			"shape": [3,3,3]
		}
	],
	"outputs": [
		{
			"name": "output",
			"type": "array",
			"shape": [3,3,3]
		}
	]
}
